### ISSUE TITLE
Directory /cmd/ or binary

### ISSUE THREAD

**Issue by xvax** [pascaldekloe/part5#1]
Hello Pascal!
Unfortunately in section ["iechbin"](https://github.com/pascaldekloe/part5#iechbin) I can't find actual binary or mentioned directory /cmd/
Could you please provide it?
The reason why I ask, because I don't understand how to execute your project

**Comment by pascaldekloe** [comment]
Hello xvax. :-) The command would be a good starting point for an example of how to use the framework indeed. Go's example tests als may help here.
You are correct about the missing parts. I managed to publish about 95% and ran out of time. The README should state that clearly. There's probably like 3 tot 4 weeks of work remaining for the finishing touch. I'm available for hire or feel free to jump in. :-)

**Comment by thibaudroy** [comment]
Hello Pascal. Following your support on https://github.com/pascaldekloe/part5/issues/4, we have now a better understanding on this project and its usage. We are willing to contribute to add support of some ASDU (_for instance 102: C_RD_NA_1 read command_).
Are you open to consider PR ? If yes, do you have some contribution guidelines ?

Also, we face `errCmdExpire` issues on some commands. We suspect the tested substation to be responsible for this. Do you have additional information / context about your [BUG: comment](https://github.com/pascaldekloe/part5/blob/master/caller.go#L383) ? That would help

Thanks !

**Comment by pascaldekloe** [comment]
Sorry for the late response @thibaudroy. Please feel free to contact me directly on pascal@quies.net. Can have phone call or chat to discuss. Contributions are most welcome. No guidelines. Just make it pretty. ✨

The expire probably needs something configurable, right? I guess the timeout can be similar for all commands send on a connection. 🤔

**Comment by pascaldekloe** [comment]
Mestral B.V. was kind enough to sponsor development. Expect good progress within a month.
