### ISSUE TITLE
Correcting size of u.info in MustNewInro

### ISSUE THREAD

**Issue by xvax** [pascaldekloe/part5#2]
Hello,
On line https://github.com/pascaldekloe/part5/blob/9302dfa5f1e4e5a2fa5818731bc73085207a5a9e/info/asdu.go#L147
and
https://github.com/pascaldekloe/part5/blob/9302dfa5f1e4e5a2fa5818731bc73085207a5a9e/info/asdu.go#L148 
need to use ObjAddrSize instead AddrSize. In constructing ASDU need to taking into account size of information object not size of common address.

**Comment by pascaldekloe** [comment]
You are correct! Thanks for reporting this issue. 👍
